/**
 * Created by Ichanskiy on 2017-04-28.
 */
INSERT INTO TAG(TAG_NAME, TAG_NAME_PARENT_FK, TAG_DISCRIPTION) VALUES ('їжа','їжа','discription');
INSERT INTO TAG(TAG_NAME, TAG_NAME_PARENT_FK, TAG_DISCRIPTION) VALUES ('одяг','одяг','discription');
INSERT INTO TAG(TAG_NAME, TAG_NAME_PARENT_FK, TAG_DISCRIPTION) VALUES ('розваги','розваги','discription');
INSERT INTO TAG(TAG_NAME, TAG_NAME_PARENT_FK, TAG_DISCRIPTION) VALUES ('подарунки','подарунки','discription');
INSERT INTO TAG(TAG_NAME, TAG_NAME_PARENT_FK, TAG_DISCRIPTION) VALUES ('ресторан','їжа','discription');
INSERT INTO TAG(TAG_NAME, TAG_NAME_PARENT_FK, TAG_DISCRIPTION) VALUES ('продукти','їжа','discription');
INSERT INTO TAG(TAG_NAME, TAG_NAME_PARENT_FK, TAG_DISCRIPTION) VALUES ('взуття','одяг','discription');
INSERT INTO TAG(TAG_NAME, TAG_NAME_PARENT_FK, TAG_DISCRIPTION) VALUES ('штани','одяг','discription');
INSERT INTO TAG(TAG_NAME, TAG_NAME_PARENT_FK, TAG_DISCRIPTION) VALUES ('верхній','одяг','discription');
INSERT INTO TAG(TAG_NAME, TAG_NAME_PARENT_FK, TAG_DISCRIPTION) VALUES ('рубашки','одяг','discription');
INSERT INTO TAG(TAG_NAME, TAG_NAME_PARENT_FK, TAG_DISCRIPTION) VALUES ('іграшки','подарунки','discription');
INSERT INTO TAG(TAG_NAME, TAG_NAME_PARENT_FK, TAG_DISCRIPTION) VALUES ('прикраси','подарунки','discription');
INSERT INTO TAG(TAG_NAME, TAG_NAME_PARENT_FK, TAG_DISCRIPTION) VALUES ('квіти','подарунки','discription');
INSERT INTO TAG(TAG_NAME, TAG_NAME_PARENT_FK, TAG_DISCRIPTION) VALUES ('атракціони','розваги','discription');
INSERT INTO TAG(TAG_NAME, TAG_NAME_PARENT_FK, TAG_DISCRIPTION) VALUES ('кінотеатр','розваги','discription');